## 用户

### 注册
POST {{url}}/user/register
Content-Type: application/json

{
  "username": "zhibi",
  "password": "12345678"
}

### 登录
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "zhibi",
  "password": "123456"
}

### 用户信息
GET {{url}}/user/info
Content-Type: application/json
Authorization: Bearer {{token}}

### 重置密码
POST {{url}}/user/resetPassword
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "4113d54f-4b98-4680-adc6-d6c9b82cdd0e",
  "password": "12345678",
  "newPassword": "123456"
}

###
## 订单

### 订单列表
POST {{url}}/order/page
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNum": 1,
  "pageSize": 10,
  "shopName": "123"
}

### 添加订单
POST {{url}}/order/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "shopName": "123456789",
  "username": "231231",
  "address": "1",
  "shopAddress": "1",
  "price": 100,
  "PaymentStatus": "1"
}

### 更新订单
POST {{url}}/order/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "f8d8ec54-9ac2-4530-922a-e836f32de1d1",
  "shopName": "123456789",
  "username": "231231",
  "address": "1",
  "shopAddress": "1",
  "price": 9,
  "PaymentStatus": "1",
  "createTime": 1651576403191,
  "updateTime": 1651890715342
}
